In [49]:
#Installing selenium
!pip install selenium

Requirement already satisfied: selenium in c:\users\suven\anaconda3\lib\site-packages (4.7.2)
Requirement already satisfied: urllib3[socks]~=1.26 in c:\users\suven\anaconda3\lib\site-packages (from selenium) (1.26.9)
Requirement already satisfied: trio-websocket~=0.9 in c:\users\suven\anaconda3\lib\site-packages (from selenium) (0.9.2)
Requirement already satisfied: certifi>=2021.10.8 in c:\users\suven\anaconda3\lib\site-packages (from selenium) (2021.10.8)
Requirement already satisfied: trio~=0.17 in c:\users\suven\anaconda3\lib\site-packages (from selenium) (0.22.0)
Requirement already satisfied: outcome in c:\users\suven\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: idna in c:\users\suven\anaconda3\lib\site-packages (from trio~=0.17->selenium) (3.3)
Requirement already satisfied: sniffio in c:\users\suven\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.2.0)
Requirement already satisfied: sortedcontainers in c:\users\suven\anaconda3\lib\site-packages (from trio~=0.17->selenium) (2.4.0)
Requirement already satisfied: async-generator>=1.9 in c:\users\suven\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.10)
Requirement already satisfied: cffi>=1.14 in c:\users\suven\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.15.0)
Requirement already satisfied: attrs>=19.2.0 in c:\users\suven\anaconda3\lib\site-packages (from trio~=0.17->selenium) (21.4.0)
Requirement already satisfied: exceptiongroup>=1.0.0rc9 in c:\users\suven\anaconda3\lib\site-packages (from trio~=0.17->selenium) (1.1.0)
Requirement already satisfied: pycparser in c:\users\suven\anaconda3\lib\site-packages (from cffi>=1.14->trio~=0.17->selenium) (2.21)
Requirement already satisfied: wsproto>=0.14 in c:\users\suven\anaconda3\lib\site-packages (from trio-websocket~=0.9->selenium) (1.2.0)
Requirement already satisfied: PySocks!=1.5.7,<2.0,>=1.5.6 in c:\users\suven\anaconda3\lib\site-packages (from urllib3[socks]~=1.26->selenium) (1.7.1)
Requirement already satisfied: h11<1,>=0.9.0 in c:\users\suven\anaconda3\lib\site-packages (from wsproto>=0.14->trio-websocket~=0.9->selenium) (0.14.0)

In [50]:
#Importing all the required libraries
import selenium
import pandas as pd
import numpy as np
from selenium import webdriver
import warnings
warnings.filterwarnings('ignore')
from selenium.webdriver.common.by import By
import time

In [51]:
#Importing exceptions
# Importing required Exceptions
from selenium.common.exceptions import StaleElementReferenceException
from selenium.common.exceptions import NoSuchElementException
from selenium.webdriver.support.ui import WebDriverWait
from selenium.webdriver.support import expected_conditions
from selenium.common.exceptions import TimeoutException

In [52]:
# importing regex
import re

# ASSIGNMENT

1. Scrape the details of most viewed videos on YouTube from Wikipedia.
Url = https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos
You need to find following details:
A) Rank
B) Name
C) Artist
D) Upload date
E) Views

In [5]:
# first, connect to the webdriver
driver=webdriver.Chrome(r"C:\Users\suven\OneDrive\Desktop\Internship\Web Scraping\Selenium\chromedriver.exe")

# getting the webpage of mentioned url
url = 'https://en.wikipedia.org/wiki/List_of_most-viewed_YouTube_videos'
driver.get(url)

In [6]:
# creating empty list for scraping the data

Rank = []
Name = []
Artist = []
Date = []
Views = []

In [7]:
# scraping Rank of the videos
try:
    for i in driver.find_elements(By.XPATH,"/html/body/div[1]/div/div[3]/main/div[2]/div[3]/div[1]/table[2]/thead/tr/th[2]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("-")

In [8]:
# scraping Rank of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("-")
        
# Scraping Name of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[2]"):
        Name.append(i.text)
except NoSuchElementException:
    Name.append("-")
        
# Scraping Artist of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[3]"):
        Artist.append(i.text)
except NoSuchElementException:
    Artist.append("-")
        
# Scraping Upload_Date of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[5]"):
        Date.append(i.text)
except NoSuchElementException:
    Date.append("-")
        
# Scraping Views of the videos
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='wikitable sortable jquery-tablesorter'][1]/tbody/tr/td[4]"):
        Views.append(i.text)
except NoSuchElementException:
    Views.append("-")

In [9]:
# creating DataFrame for scraped data
Wiki = pd.DataFrame({})
Wiki['Rank'] = Rank
Wiki['Name'] = Name
Wiki['Artist'] = Artist
Wiki['Upload Date'] = Date
Wiki['Views (in Billions)'] = Views

# removing stray numbers from Name column
Wiki.Name = Wiki.Name.apply(lambda x:x[:-4].strip('"'))
Wiki

,Rank,Name,Artist,Upload Date,Views (in Billions)
0,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",12.3
1,2.,Despacito,Luis Fonsi,"January 12, 2017",8.1
2,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",6.59
3,4.,Bath Song,Cocomelon â€“ Nursery Rhymes,"May 2, 2018",5.96
4,5.,Shape of You,Ed Sheeran,"January 30, 2017",5.89
5,6.,See You Again,Wiz Khalifa,"April 6, 2015",5.76
6,7.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",5.12
7,8.,Wheels on the Bus,Cocomelon â€“ Nursery Rhymes,"May 24, 2018",4.84
8,9.,Uptown Funk,Mark Ronson,"November 19, 2014",4.82
9,10.,Learning Colors â€“ Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.8
10,11.,Gangnam Style,Psy,"July 15, 2012",4.66
11,12.,Masha and the Bear â€“ Recipe for Disaster,Get Movies,"January 31, 2012",4.52
12,13.,Dame Tu Cosita,El Chombo,"April 5, 2018",4.21
13,14.,Sugar,Maroon 5,"January 14, 2015",3.81
14,15.,Roar,Katy Perry,"September 5, 2013",3.72
15,16.,Counting Stars,OneRepublic,"May 31, 2013",3.71
16,17.,Axel F,Crazy Frog,"June 16, 2009",3.71
17,18.,Sorry,Justin Bieber,"October 22, 2015",3.62
18,19.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.54
19,20.,Baa Baa Black Sheep,Cocomelon â€“ Nursery Rhymes,"June 25, 2018",3.48
20,21.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",3.44
21,22.,Dark Horse,Katy Perry,"February 20, 2014",3.43
22,23.,Faded,Alan Walker,"December 3, 2015",3.39
23,24.,Let Her Go,Passenger,"July 25, 2012",3.37
24,25.,Girls Like You,Maroon 5,"May 31, 2018",3.36
25,26.,Perfect,Ed Sheeran,"November 9, 2017",3.35
26,27.,Bailando,Enrique Iglesias,"April 11, 2014",3.32
27,28.,Lean On,Major Lazer,"March 22, 2015",3.32
28,29.,Humpty the train on a fruits ride,Kiddiestv Hindi â€“ Nursery Rhymes & Kids Songs,"January 26, 2018",3.29
29,30.,Lakdi Ki Kathi,Jingle Toons,"June 14, 2018",3.26
30,1.,Baby Shark Dance,Pinkfong Baby Shark - Kids' Songs & Stories,"June 17, 2016",12.3
31,2.,Despacito,Luis Fonsi,"January 12, 2017",8.1
32,3.,Johny Johny Yes Papa,LooLoo Kids,"October 8, 2016",6.59
33,4.,Bath Song,Cocomelon â€“ Nursery Rhymes,"May 2, 2018",5.96
34,5.,Shape of You,Ed Sheeran,"January 30, 2017",5.89
35,6.,See You Again,Wiz Khalifa,"April 6, 2015",5.76
36,7.,Phonics Song with Two Words,ChuChu TV,"March 6, 2014",5.12
37,8.,Wheels on the Bus,Cocomelon â€“ Nursery Rhymes,"May 24, 2018",4.84
38,9.,Uptown Funk,Mark Ronson,"November 19, 2014",4.82
39,10.,Learning Colors â€“ Colorful Eggs on a Farm,Miroshka TV,"February 27, 2018",4.8
40,11.,Gangnam Style,Psy,"July 15, 2012",4.66
41,12.,Masha and the Bear â€“ Recipe for Disaster,Get Movies,"January 31, 2012",4.52
42,13.,Dame Tu Cosita,El Chombo,"April 5, 2018",4.21
43,14.,Sugar,Maroon 5,"January 14, 2015",3.81
44,15.,Roar,Katy Perry,"September 5, 2013",3.72
45,16.,Counting Stars,OneRepublic,"May 31, 2013",3.71
46,17.,Axel F,Crazy Frog,"June 16, 2009",3.71
47,18.,Sorry,Justin Bieber,"October 22, 2015",3.62
48,19.,Thinking Out Loud,Ed Sheeran,"October 7, 2014",3.54
49,20.,Baa Baa Black Sheep,Cocomelon â€“ Nursery Rhymes,"June 25, 2018",3.48
50,21.,Waka Waka (This Time for Africa),Shakira,"June 4, 2010",3.44
51,22.,Dark Horse,Katy Perry,"February 20, 2014",3.43
52,23.,Faded,Alan Walker,"December 3, 2015",3.39
53,24.,Let Her Go,Passenger,"July 25, 2012",3.37
54,25.,Girls Like You,Maroon 5,"May 31, 2018",3.36
55,26.,Perfect,Ed Sheeran,"November 9, 2017",3.35
56,27.,Bailando,Enrique Iglesias,"April 11, 2014",3.32
57,28.,Lean On,Major Lazer,"March 22, 2015",3.32
58,29.,Humpty the train on a fruits ride,Kiddiestv Hindi â€“ Nursery Rhymes & Kids Songs,"January 26, 2018",3.29
59,30.,Lakdi Ki Kathi,Jingle Toons,"June 14, 2018",3.26

In [9]:
driver.close()

------

2. Scrape the details team Indiaâ€™s internationalfixtures from bcci.tv. 
Url = https://www.bcci.tv/.
You need to find following details:
A) Match title (I.e. 1stODI)
B) Series
C) Place
D) Date
E) Time
Note: - From bcci.tv home page you have reach to the international fixture page through code.

In [34]:
# first, connect to the webdriver
driver=webdriver.Chrome(r"C:\Users\suven\OneDrive\Desktop\Internship\Web Scraping\Selenium\chromedriver.exe")

# getting the webpage of mentioned url
url = 'https://www.bcci.tv/'
driver.get(url)

In [35]:

btn=driver.find_element(By.XPATH,"/html/body/nav/div[1]/div[2]/ul[1]/li[2]/a")
btn.click()

In [40]:
# creating empty lists for scraping the data
Match_Title = []
Series = []
Place = []
Date = []
Time = []

In [52]:
# Scraping details from the website

for i in driver.find_elements(By.XPATH,"//div[@class='fix-place ng-binding ng-scope']/span[@class='matchOrderText ng-binding ng-scope']"):
    Match_Title.append(i.text)
    
for i in driver.find_elements(By.XPATH,"//h5[@class='fix-text']/span[@class='ng-binding']"):
    Series.append(i.text)
    
for i in driver.find_elements(By.XPATH,"//div[@class='fix-place ng-binding ng-scope']/span[@class='ng-binding ng-scope']"):
    Place.append(i.text)
        
for i in driver.find_elements(By.XPATH,"//h5[@class='ng-binding']"):
    Date.append(i.text.replace('\n',' '))

for i in driver.find_elements(By.XPATH,"//h5[@class='text-right ng-binding']"):
    Time.append(i.text.replace('\n',' '))
    

date=[i.split(' ',3)[:3] for i in Date]
date=[' '.join(i) for i in date]


# creating data frame
fixture=pd.DataFrame({'Match Title': Match_Title,
                         "Series": Series,
                         "Place": Place,
                          "Date": date,
                          "Time": Time})
fixture

,Match Title,Series,Place,Date,Time
0,1st Test -,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,"Vidarbha Cricket Association Stadium,",9 FEB 2023,9:30 AM IST
1,1st T20I -,ICC WOMENS T20 WORLD CUP 2023,"Newlands,",12 FEB 2023,6:30 PM IST
2,2nd T20I -,ICC WOMENS T20 WORLD CUP 2023,"Newlands,",15 FEB 2023,6:30 PM IST
3,2nd Test -,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,"Arun Jaitley Stadium,",17 FEB 2023,9:30 AM IST
4,3rd T20I -,ICC WOMENS T20 WORLD CUP 2023,"St George's Park,",18 FEB 2023,6:30 PM IST
...,...,...,...,...,...
59,2nd Test -,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,"Arun Jaitley Stadium,",17 FEB 2023,9:30 AM IST
60,3rd T20I -,ICC WOMENS T20 WORLD CUP 2023,"St George's Park,",18 FEB 2023,6:30 PM IST
61,4th T20I -,ICC WOMENS T20 WORLD CUP 2023,"St George's Park,",20 FEB 2023,6:30 PM IST
62,3rd Test -,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,"Himachal Pradesh Cricket Association Stadium,",1 MAR 2023,9:30 AM IST
63,4th Test -,AUSTRALIA TOUR OF INDIA TEST SERIES 2022-23,"Narendra Modi Stadium,",9 MAR 2023,9:30 AM IST

In [33]:
driver.close()

3. Scrape the details of State-wise GDP ofIndia fromstatisticstime.com. 
Url = http://statisticstimes.com/
You have to find following details:
A) Rank
B) State
C) GSDP(18-19)- at current prices
D) GSDP(19-20)- at current prices
E) Share(18-19)
F) GDP($ billion)
Note: - From statisticstimes home page you have to reach to economy page through code.

In [27]:
# connecting to the web driver
driver=webdriver.Chrome(r"C:\Users\suven\OneDrive\Desktop\Internship\Web Scraping\Selenium\chromedriver.exe")

# getting the webpage of mentioned url
url = ("http://statisticstimes.com/")
driver.get(url)

In [28]:
# clicking on Economy button
driver.find_element(By.XPATH,"/html/body/div[2]/div[1]/div[2]/div[2]/button").click()

# clicking on India
driver.find_element(By.XPATH,"/html/body/div[2]/div[1]/div[2]/div[2]/div/a[3]").click()
time.sleep(3)

# clicking on GDP of Indian Economy
GDP = driver.find_element(By.XPATH,"/html/body/div[2]/div[2]/div[2]/ul/li[1]/a").click()
time.sleep(3)

In [29]:
# creating empty list
Rank = []
State = []
GSDP1 = []
GSDP2 = []
Share = []
GDP_billion = []

In [31]:
# scraping Rank
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[1]"):
        Rank.append(i.text)
except NoSuchElementException:
    Rank.append("_")
    
# scraping State
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[2]"):
        State.append(i.text)
except NoSuchElementException:
    State.append("_")
    
# scraping GSDP at current price (19-20)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[3]"):
        GSDP1.append(i.text)
except NoSuchElementException:
    GSDP1.append("_")
    
# scraping GSDP at current price (18-19)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[4]"):
        GSDP2.append(i.text)
except NoSuchElementException:
    GSDP2.append("_")
    
# scraping Share (18-19)
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[5]"):
        Share.append(i.text)
except NoSuchElementException:
    Share.append("_")
    
# scraping GDP $ billion
try:
    for i in driver.find_elements(By.XPATH,"//table[@class='display dataTable']/tbody/tr/td[6]"):
        GDP_billion.append(i.text)
except NoSuchElementException:
    GDP_billion.append("_")

In [32]:
# creating DataFrame from the scraped data
GDP = pd.DataFrame({})
GDP['Rank'] = Rank
GDP['State'] = State
GDP['GSDP at current price (19-20)'] = GSDP1
GDP['GSDP at current price (18-19)'] = GSDP2
GDP['Share (18-19)'] = Share
GDP['GDP($ billion)'] = GDP_billion
GDP

,Rank,State,GSDP at current price (19-20),GSDP at current price (18-19),Share (18-19),GDP($ billion)
0,1,Maharashtra,-,"2,632,792",13.94%,399.921
1,2,Tamil Nadu,"1,845,853","1,630,208",8.63%,247.629
2,3,Uttar Pradesh,"1,687,818","1,584,764",8.39%,240.726
3,4,Gujarat,-,"1,502,899",7.96%,228.290
4,5,Karnataka,"1,631,977","1,493,127",7.91%,226.806
...,...,...,...,...,...,...
127,29,Sikkim,"28,391","25,141",0.15%,"17,060"
128,30,Nagaland,-,"24,534",0.15%,-
129,31,Arunachal Pradesh,-,"22,488",0.13%,-
130,32,Mizoram,"24,424","20,947",0.13%,"17,797"
131,33,Andaman & Nicobar Islands,-,-,-,-

In [ ]:
driver.close()

4. Scrape the details of trending repositories on Github.com. 
Url = https://github.com/
You have to find the following details:
A) Repository title
B) Repository description
C) Contributors count
D) Language used
ASSIGNMENT
Note: - From the home page you have to click on the trending option from Explore menu through code.

In [80]:
# connecting to the web driver
driver=webdriver.Chrome(r"C:\Users\suven\OneDrive\Desktop\Internship\Web Scraping\Selenium\chromedriver.exe")

# getting the webpage of mentioned url
url = ("https://github.com/")
driver.get(url)

In [81]:
# getting explore button and clicking on it

open_source_btn=driver.find_element(By.XPATH,'/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/button').click()

# selecting trending option
trend_url = driver.find_element(By.XPATH,"/html/body/div[1]/div[1]/header/div/div[2]/div/nav/ul/li[3]/div/ul[3]/li[3]/a")
urls = trend_url.get_attribute("href")
driver.get(urls)

In [82]:
# creating empty list
URLs = []
repository_title = []
Description = []
Contributors = []
Language = []
lang = []

In [ ]:
# fetching urls for each repository
repository = driver.find_elements(By.XPATH,"//h1[@class='h3 lh-condensed']//a")
for i in repository:
    URLs.append(i.get_attribute("href"))
    
# scraping Repository title data
title = driver.find_elements(By.XPATH,"//h1[@class = 'h3 lh-condensed']")
for i in title:
    repository_title.append(i.text)
    
# scraping data from all repository page
for i in URLs:
    driver.get(i)
    time.sleep(5)
    
    # scraping Repository Description data 
    try:
        desc = driver.find_element(By.XPATH,"//p[@class='f4 mt-3']")
        Description.append(desc.text)
    except NoSuchElementException:
        Description.append('-')
        
        
    # scraping Contributors Count data
    try:
        contributor = driver.find_element(By.XPATH,"//*[contains(text(),'    Contributors ')]")
        Contributors.append(contributor.text.replace('Contributors',''))
    except NoSuchElementException:
        Contributors.append('-')
    
    
    # scraping Languages used data
    try:
        for i in driver.find_elements(By.XPATH,"//ul[@class= 'list-style-none']//li//span[1]"):
            lang.append(i.text)
        Language.append(lang)
    except NoSuchElementException:
        Language.append('-')

# Data Framing
Github = pd.DataFrame({})
Github['Repository Title'] = repository_title[0:3]
Github['Repository Description'] = Description[0:3]
Github['Contributors Count'] = Contributors[0:3]
Github['Language Used'] = Language[0:3]
Github

In [17]:
driver.close()

------

5. Scrape the details of top 100 songs on billiboard.com. 
Url = https:/www.billboard.com/
You have to find the following details:
A) Song name
B) Artist name
C) Last week rank
D) Peak rank
E) Weeks on board
Note: - From the home page you have to click on the charts option then hot 100-page link through code.

In [37]:
# connecting to the web driver
driver=webdriver.Chrome(r"C:\Users\suven\OneDrive\Desktop\Internship\Web Scraping\Selenium\chromedriver.exe")

# getting the webpage of mentioned url
url = ("https://www.billboard.com/")
driver.get(url)

In [38]:
# clicking on option button
charts=driver.find_element(By.XPATH,"/html/body").click()

In [39]:
# creating empty lists
Song_Name = []
Artist_Name =[]
Last_week_rank = []
Peak_rank = []
Weeks_on_board = []

In [21]:
print(len(Song_Name),len(Artist_Name),len(Last_week_rank),len(Peak_rank),len(Weeks_on_board))

200 200 198 99 198

In [40]:
#getting urls for top 100 songs
urls = driver.find_element(By.XPATH,"//h3[@class='c-title  a-font-primary-medium-xs']//a")
page_url = urls.get_attribute("href")
driver.get(page_url)
time.sleep(4)

In [41]:
# scraping data of song names
for i in driver.find_elements(By.XPATH,"//li[@class='lrv-u-width-100p']//h3"):
    Song_Name.append(i.text)
    
# scraping data of artist names
for i in driver.find_elements(By.XPATH,'//li[@class="lrv-u-width-100p"]/ul/li[1]/span'):
    Artist_Name.append(i.text)
    
# scraping data of last week ranks
for i in driver.find_elements(By.XPATH,"//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max']/span[@class='c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max']"):
    Last_week_rank.append(i.text)
    

# scraping data of peak ranks
for i in driver.find_elements(By.XPATH,"//li[@class='o-chart-results-list__item // a-chart-bg-color a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-background-color-grey-lightest lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-hidden@mobile-max']/span[@class='c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max']"):
    Peak_rank.append(i.text)       
    
    
# scraping data of weeks on board
for i in driver.find_elements(By.XPATH,"//li[@class='o-chart-results-list__item // a-chart-color u-width-72 u-width-55@mobile-max u-width-55@tablet-only lrv-u-flex lrv-u-flex-shrink-0 lrv-u-align-items-center lrv-u-justify-content-center lrv-u-border-b-1 u-border-b-0@mobile-max lrv-u-border-color-grey-light u-background-color-white-064@mobile-max u-hidden@mobile-max']/span[@class='c-label  a-font-primary-m lrv-u-padding-tb-050@mobile-max']"):
    Weeks_on_board.append(i.text)
    
    
# creating dataframe for scraped data
billiboard = pd.DataFrame({})
billiboard['Name'] = Song_Name[0:99]
billiboard['Artist'] = Artist_Name[0:99]
billiboard['Last Week Rank'] = Last_week_rank[0:99]
billiboard['Peak Rank'] = Peak_rank[0:99]
billiboard['Weeks on board'] = Weeks_on_board[0:99]
billiboard

,Name,Artist,Last Week Rank,Peak Rank,Weeks on board
0,Flowers,Miley Cyrus,2,2,2
1,Kill Bill,SZA,8,3,8
2,Creepin',"Metro Boomin, The Weeknd & 21 Savage",4,1,4
3,Anti-Hero,Taylor Swift,9,1,9
4,Unholy,Sam Smith & Kim Petras,3,6,3
...,...,...,...,...,...
94,Next Thing You Know,Jordan Davis,45,96,45
95,Hey Mor,Ozuna Featuring Feid,30,60,30
96,Gato de Noche,Nengo Flow & Bad Bunny,48,83,48
97,Heart To Heart,Mac DeMarco,38,99,38
98,Never Gonna Not Dance Again,P!nk,44,100,44

In [42]:
driver.close()

------

6. Scrape the details of Highest sellingnovels.
Url = https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-greycompare/
You have to find the following details:
A) Book name
B) Author name
C) Volumes sold
D) Publisher
E) Genre

In [28]:
# connecting to the web driver
driver=webdriver.Chrome(r"C:\Users\suven\OneDrive\Desktop\Internship\Web Scraping\Selenium\chromedriver.exe")

# getting the webpage of mentioned url
url = ("https://www.theguardian.com/news/datablog/2012/aug/09/best-selling-books-all-time-fifty-shades-grey-compare/")
driver.get(url)
time.sleep(3)

In [29]:
# creating empty lists
Book_name = []
Author_name = []
Volumes_sold = []
Publisher = []
Genre = []

In [30]:
# scraping book names data
for i in driver.find_elements(By.XPATH,"//tbody//tr//td[2]"):
    Book_name.append(i.text)

    
# scraping author names data
for i in driver.find_elements(By.XPATH,"//tbody//tr//td[3]"):
    try:
        if i.text == '0' : raise NoSuchElementException
        Author_name.append(i.text)
    except NoSuchElementException:
        Author_name.append('-')
time.sleep(3)


# scraping data of volumes sold
for i in driver.find_elements(By.XPATH,"//tbody//tr//td[4]"):
    Volumes_sold.append(i.text)
    
    
# scraping data of publisher names
for i in driver.find_elements(By.XPATH,"//tbody//tr//td[5]"):
    Publisher.append(i.text)
    
    
# scraping  data of genre
for i in driver.find_elements(By.XPATH,"//tbody//tr//td[6]"):
    Genre.append(i.text)    
    
    
# creating dataframe for scraped data
Novels = pd.DataFrame({})
Novels['Book Name'] = Book_name
Novels['Author'] = Author_name
Novels['Volume sold'] = Volumes_sold
Novels['Publisher'] = Publisher
Novels['Genre'] = Genre
Novels

,Book Name,Author,Volume sold,Publisher,Genre
0,"Da Vinci Code,The","Brown, Dan","5,094,805",Transworld,"Crime, Thriller & Adventure"
1,Harry Potter and the Deathly Hallows,"Rowling, J.K.","4,475,152",Bloomsbury,Children's Fiction
2,Harry Potter and the Philosopher's Stone,"Rowling, J.K.","4,200,654",Bloomsbury,Children's Fiction
3,Harry Potter and the Order of the Phoenix,"Rowling, J.K.","4,179,479",Bloomsbury,Children's Fiction
4,Fifty Shades of Grey,"James, E. L.","3,758,936",Random House,Romance & Sagas
...,...,...,...,...,...
95,"Ghost,The","Harris, Robert","807,311",Random House,General & Literary Fiction
96,Happy Days with the Naked Chef,"Oliver, Jamie","794,201",Penguin,Food & Drink: General
97,"Hunger Games,The:Hunger Games Trilogy","Collins, Suzanne","792,187",Scholastic Ltd.,Young Adult Fiction
98,"Lost Boy,The:A Foster Child's Search for the L...","Pelzer, Dave","791,507",Orion,Biography: General
99,Jamie's Ministry of Food:Anyone Can Learn to C...,"Oliver, Jamie","791,095",Penguin,Food & Drink: General

In [ ]:
driver.close()

-----

7. Scrape the details most watched tv series of all time from imdb.com. 
Url = https://www.imdb.com/list/ls095964455/
You have to find the following details:
A) Name
B) Year span
C) Genre
D) Run time
E) Ratings
F) Votes

In [35]:
# connecting to the web driver
driver=webdriver.Chrome(r"C:\Users\suven\OneDrive\Desktop\Internship\Web Scraping\Selenium\chromedriver.exe")

# getting the webpage of mentioned url
url = ("https://www.imdb.com/list/ls095964455/")
driver.get(url)

In [36]:
# creating empty lists
Name = []
Year_span = []
Genre = []
Run_time = []
Ratings = []
Votes = []

In [37]:
# scraped data of Names
for i in driver.find_elements(By.XPATH,"//h3[@class='lister-item-header']/a"):
    Name.append(i.text)
    
    
# scraped data of Year span
for i in driver.find_elements(By.XPATH,"//span[@class='lister-item-year text-muted unbold']"):
    Year_span.append(i.text)
    
    
# scraped data of Genre
for i in driver.find_elements(By.XPATH,"//span[@class='genre']"):
    Genre.append(i.text)
    
    
# scraped data of Run time
for i in driver.find_elements(By.XPATH,"//span[@class='runtime']"):
    Run_time.append(i.text)
    
    
# scraped data of Ratings
for i in driver.find_elements(By.XPATH,"//div[@class='ipl-rating-star small']//span[2]"):
    Ratings.append(i.text)
    
    
# scraped data of Votes
for i in driver.find_elements(By.XPATH,"//div[@class='lister-item-content']//p[4]/span[2]"):
    Votes.append(i.text) 
    
    
# creating dataframe for scraped data
TV_Series = pd.DataFrame({})
TV_Series['Name'] = Name
TV_Series['Year Span'] = Year_span
TV_Series['Genre'] = Genre
TV_Series['Run Time'] = Run_time
TV_Series['Ratings'] = Ratings
TV_Series['Votes'] = Votes
TV_Series

,Name,Year Span,Genre,Run Time,Ratings,Votes
0,Game of Thrones,(2011â€“2019),"Action, Adventure, Drama",57 min,9.2,"2,120,851"
1,Stranger Things,(2016â€“2024),"Drama, Fantasy, Horror",51 min,8.7,"1,209,311"
2,The Walking Dead,(2010â€“2022),"Drama, Horror, Thriller",44 min,8.1,"1,005,722"
3,13 Reasons Why,(2017â€“2020),"Drama, Mystery, Thriller",60 min,7.5,"296,825"
4,The 100,(2014â€“2020),"Drama, Mystery, Sci-Fi",43 min,7.6,"255,776"
...,...,...,...,...,...,...
95,Reign,(2013â€“2017),Drama,42 min,7.4,"50,694"
96,A Series of Unfortunate Events,(2017â€“2019),"Adventure, Comedy, Drama",50 min,7.8,"62,574"
97,Criminal Minds,(2005â€“ ),"Crime, Drama, Mystery",42 min,8.1,"202,583"
98,Scream: The TV Series,(2015â€“2019),"Comedy, Crime, Drama",45 min,7.1,"42,018"
99,The Haunting of Hill House,(2018),"Drama, Horror, Mystery",572 min,8.6,"250,408"

In [ ]:
driver.close()

----

8. Details of Datasets from UCI machine learning repositories. 
Url = https://archive.ics.uci.edu/
You have to find the following details:
A) Dataset name
B) Data type
C) Task
D) Attribute type
E) No of instances
F) No of attribute
G) Year
Note: - from the home page you have to go to the ShowAllDataset page through code.

In [43]:
# connecting to the web driver
driver=webdriver.Chrome(r"C:\Users\suven\OneDrive\Desktop\Internship\Web Scraping\Selenium\chromedriver.exe")

# getting the webpage of mentioned url
url = (" https://archive.ics.uci.edu/")
driver.get(url)

In [44]:
# fetching view all dataset button from the webpage
viewall_dataset = driver.find_element(By.XPATH,"//tbody[1]//tr/td[2]/span[2]/a")
page_url = viewall_dataset.get_attribute("href")
driver.get(page_url)
time.sleep(3)

In [45]:
# fetching page urls of all datasets
view_list = driver.find_element(By.XPATH,"/html/body/table[2]/tbody/tr/td[2]/table[1]/tbody/tr/td[2]/p/a")
list_url = view_list.get_attribute("href")
driver.get(list_url)
time.sleep(3)

In [46]:
# fetching urls for each dataset
dataset_url = driver.find_elements(By.XPATH,"//p[@class='normal']//b/a")

urls = []
for i in dataset_url:
    urls.append(i.get_attribute("href"))

In [47]:
# creating empty lists
Dataset_name = []
Data_type = []
Task = []
Attribute_type = []
No_of_instances = []
No_of_attributes = []
Year = []

In [ ]:
for i in urls:
    driver.get(i)
    time.sleep(3)
    
    
    # scraping  Dataset name
    try:
        dataset_name = driver.find_element(By.XPATH,"//span[@class='heading']")
        Dataset_name.append(dataset_name.text)
    except NoSuchElementException:
        Dataset_name.append('-')
    time.sleep(3)
    
    
    
    # scraping data type
    try:
        data_type = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr/td[2]")
        if data_type.text == "N/A": raise NoSuchElementException
        Data_type.append(data_type.text)
    except NoSuchElementException:
        Data_type.append('-')
    time.sleep(3)
    
    
    # scraping Task
    try:
        task = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[3]/td[2]")
        if task.text == "N/A": raise NoSuchElementException
        Task.append(task.text)
    except NoSuchElementException:
        Task.append('-')
    time.sleep(3)
    
    
    
    # scraping Attribute type
    try:
        attribute_type = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[2]")
        if attribute_type.text == "N/A": raise NoSuchElementException
        Attribute_type.append(attribute_type.text)
    except NoSuchElementException:
        Attribute_type.append('-')
    time.sleep(3)
    
    
    
    # scraping No of Instances
    try:
        instances = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr/td[4]")
        if instances.text == "N/A": raise NoSuchElementException
        No_of_instances.append(instances.text)
    except NoSuchElementException:
        No_of_instances.append('-')
    time.sleep(3)
    
    
    
    # scraping No of Arrtibutes
    try:
        attribute = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[4]")
        if attribute.text == "N/A": raise NoSuchElementException
        No_of_attributes.append(attribute.text)
    except NoSuchElementException:
        No_of_attributes.append('-')
    time.sleep(3)
    
    
    # scraping Year
    try:
        year = driver.find_element(By.XPATH,"//table[@border='1']//tbody/tr[2]/td[6]")
        if year.text == "N/A": raise NoSuchElementException
        Year.append(year.text[:4])
    except NoSuchElementException:
        Year.append('-')
    time.sleep(3)
    

    # creating dataframe for scraped data
ML = pd.DataFrame({})
ML['Data Name'] = Data_name[0:5]
ML['Data Type '] = Data_type[0:5]
ML['Task '] = Task[0:5]
ML['Attribute Type '] = Attribute_type[0:5]
ML['No of Instance '] = No_of_instances[0:5]
ML['No of Attributes '] = No_of_attributes[0:5] 
ML['Year '] = Year 
ML

In [ ]:

driver.close()

# -- The End --